=== microsoft/microsoft-performance-toolkit-sdk/src/PluginsSystem/Schemas/PluginManifestSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "JSON Schema a plugin manifest",
  "type": "object",
  "required": [
    "identity",
    "displayName",
    "description",
    "projectUrl",
    "owners"
  ],
  "properties": {
    "identity": {
      "type": "object",
      "required": [
        "id",
        "version"
      ],
      "properties": {
        "id": {
          "type": "string",
          "description": "The unique identifier for a plugin."
        },
        "version": {
          "type": "string",
          "pattern": "^(\\d+\\.\\d+\\.\\d+)(?:-([0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*))?(?:\\+([0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*))?$",
          "description": "The version number of the plugin."
        }
      }
    },
    "description": {
      "type": "string",
      "description": "A short description of the plugin."
    },
    "displayName": {
      "type": "string",
      "description": "This shows up in tooltips for the 'name' property."
    },
    "projectUrl": {
      "type": "string",
      "format": "uri",
      "description": "The URL of the project's home page."
    },
    "owners": {
      "type": "array",
      "description": "The owners of the plugin.",
      "required": [
        "name",
        "address",
        "emailAddresses",
        "phoneNumbers"
      ],
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "The name of the owner."
          },
          "address": {
            "type": "string",
            "description": "The address of the owner."
          },
          "emailAddresses": {
            "type": "array",
            "items": {
              "type": "string",
              "format": "email",
              "description": "The email address of the owner."
            }
          },
          "phoneNumbers": {
            "type": "array",
            "items": {
              "type": "string",
              "description": "The phone number of the owner."
            }
          }
        }
      }
    },
    "manifestVersion": {
      "type": "number",
      "description": "The version of the manifest schema.",
      "const": 1.0
    }
  }
}

=== microsoft/microsoft-performance-toolkit-sdk/devel-template/templates/PluginTemplate/pluginManifest.json
{
  "$schema": "https://raw.githubusercontent.com/microsoft/microsoft-performance-toolkit-sdk/feature/pluginToolCli/src/PluginsSystem/Tools/Microsoft.Performance.Toolkit.Plugins.Cli/Schemas/PluginManifestSchema.json",
  "identity": {
    "id": "__PLUGIN_ID__",
    "version": "__PLUGIN_VERSION__"
  },
  "description": "__PLUGIN_DESCRIPTION__",
  "displayName": "__PLUGIN_DISPLAY_NAME__",
  "owners": [
    {
      "name": "__PLUGIN_OWNER_NAME__",
      "address": "__PLUGIN_OWNER_ADDRESS__",
      "emailAddresses": [ "__PLUGIN_OWNER_EMAIL__A__", "__PLUGIN_OWNER_EMAIL__B__" ],
      "phoneNumbers": [ "__PLUGIN_OWNER_PHONE__A__", "__PLUGIN_OWNER_PHONE__B__" ]
    }
  ],
  "projectUrl": "__PLUGIN_PROJECT_URL__",
  "manifestVersion": 1.0
}
